controller_list:
  - name: fake_arm_widowx_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_gripper_widowx_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_joint
initial:  # Define initial robot poses per group
  - group: arm_widowx
    pose: home
  - group: gripper_widowx
    pose: open